### ISSUE TITLE
Unnecessary math3d::Ray copying

### ISSUE THREAD

**Issue by BlackSamorez** [galqiwi/raytracer21#1]
https://github.com/galqiwi/raytracer21/blob/e003ea9e72a64ad9fc61c12795ef16cdab541c07/src/raytracer/Sky.hpp#L16

ray acts like const reference

**Comment by BlackSamorez** [comment]
@galqiwi

**Comment by galqiwi** [comment]
Этот проект by design не поддерживается, закрываю issue
